### ISSUE TITLE
[인프런] 스프링부트와 JPA 활용1

### ISSUE THREAD

**Issue by sw-develop** [sw-develop/for-Spring#4]
### TODO
- [x] 프로젝트 환경설정(H2 데이터베이스와 JPA 설정, 동작확인)
- [x] 도메인 분석 설계(도메인 모델, 테이블, 엔티티 클래스)
- [x] 회원 도메인 개발
- [x] 상품 도메인 개발
- [x] 주문 도메인 개발
- [x] 웹 계층 개발
